if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="EGMO-sols-3";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import graph;
import olympiad;
import cse5;
defaultpen(fontsize(10pt));
usepackage("amsmath");
usepackage("amssymb");
settings.tex="latex";
settings.outformat="pdf";
size(10cm);

pair A = dir(120);
pair B = dir(210);
pair C = dir(330);
path ABC = circumcircle(A,B,C);
draw(A--B--C--cycle);
draw(ABC);
pair K = foot(A,B,C);
pair Aprime = midpoint(B--C);
pair Bprime = midpoint(C--A);
pair Cprime = midpoint(A--B);
draw(circumcircle(Aprime,Bprime,Cprime));
pair G = centroid(A,B,C);
draw(A--Aprime);
draw(B--Bprime);
draw(C--Cprime);
draw(Aprime--Bprime);
draw(Bprime--Cprime);
draw(Cprime--Aprime);
path AX = L(A, (1, ypart(A)));
pair [] X = IPs(AX,ABC);
pair X = X[1];
draw(A--X);
draw(K--X);
draw(A--K);
draw(rightanglemark(A,K,C,3));
draw(rightanglemark(K,A,X,3));

dot("$A$", A, dir(A));
dot("$B$", B, dir(B));
dot("$C$", C, dir(C));
dot("$K$", K, dir(K));
dot("$A'$", Aprime, dir(Aprime));
dot("$B'$", Bprime, dir(Bprime));
dot("$C'$", Cprime, dir(Cprime));
dot("$G$", G, dir(0));
dot("$X$", X, dir(X));
